version: '3'

services:
  app:
    container_name: springboot
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  front:
    container_name: semka24
    build: ./front/
    ports:
      - "8888:80"
    depends_on:
      - app
  postgres:
    image: postgres
    #    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
